### ISSUE TITLE
Problem running on node under Ubuntu

### ISSUE THREAD

**Issue by cloojure** [funcool/clojurescript-unraveled#118]
Hi - reading section 4.1.3 I am trying to run under Node.js and get an error.  It appears that references to the google closure compiler libs are not being included correctly(?).  Output:

```
~/work/clojurescript-unraveled/myapp > cat src/myapp/core.cljs 
(ns myapp.core
  (:require [cljs.nodejs :as nodejs] ))

(nodejs/enable-util-print!)

(defn -main  [& args]
  (println "Hello world!"))

(set! *main-cli-fn* -main)

~/work/clojurescript-unraveled/myapp > cat build.clj
(require '[cljs.build.api :as b] )

(b/build "src"    {:main          'myapp.core
                   :output-to     "main.js"
                   :output-dir    "out"
                   :target        ":nodejs"
                   :verbose       true } )

~/work/clojurescript-unraveled/myapp > java -cp cljs.jar:src clojure.main build.clj
~/work/clojurescript-unraveled/myapp > java -version
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
~/work/clojurescript-unraveled/myapp > node --version
v5.4.1
~/work/clojurescript-unraveled/myapp > 
~/work/clojurescript-unraveled/myapp > d *
-rw-rw-r-- 1 alan alan      254 Apr  2 19:26 build.clj
-rw-rw-r-- 1 alan alan 20078770 Apr  2 19:30 cljs.jar
-rw-rw-r-- 1 alan alan      430 Apr  2 19:45 main.js
drwxrwxr-x 5 alan alan     4096 Apr  2 19:33 out/
drwxrwxr-x 3 alan alan     4096 Apr  2 19:23 src/
~/work/clojurescript-unraveled/myapp > node main.js
/home/alan/work/clojurescript-unraveled/myapp/main.js:2
if(typeof goog == "undefined") document.write('<script src="out/goog/base.js"></script>');
                               ^

ReferenceError: document is not defined
    at Object.<anonymous> (/home/alan/work/clojurescript-unraveled/myapp/main.js:2:32)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:429:10)
    at startup (node.js:139:18)
    at node.js:999:3
~/work/clojurescript-unraveled/myapp > 

```

**Comment by niwinz** [comment]
The problem comes from your `:target ":nodejs"`. `:nodejs` should be as is, without quoting.

**Comment by cloojure** [comment]
Doh!   (works great now).
